import { access, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { loadPlugin } from '../../core/plugin-loader.js';

export interface InitCommandOptions {
  plugin: string;
  output: string;
  force?: boolean;
}

export async function initCommand(options: InitCommandOptions): Promise<void> {
  const pluginPath = resolve(options.plugin);
  const outputPath = resolve(options.output);

  const plugin = await loadPlugin(pluginPath);
  const uniqueTargets = [...new Set(plugin.templates.map((t) => t.target))].sort();

  let exists = false;
  try {
    await access(outputPath);
    exists = true;
  } catch {
    // File does not exist — good, we'll create it.
  }

  if (exists && !options.force) {
    throw new Error(
      `Config file already exists: ${outputPath}\nUse --force to overwrite.`,
    );
  }

  const today = new Date().toISOString().split('T')[0];
  const lines = [
    `# Boilergen configuration for this project.`,
    `# Generated by 'boilergen init' on ${today}.`,
    ``,
    `# Path to the boilergen plugin (absolute or relative to this config file).`,
    `plugin: ${pluginPath}`,
    ``,
    `# Where each target's generated files should land in your project tree.`,
    `# Replace ./TODO with the actual destination paths.`,
    `targets:`,
    ...uniqueTargets.map((t) => `  ${t}: ./TODO  # destination for ${t} target`),
    ``,
  ];

  await writeFile(outputPath, lines.join('\n'), 'utf-8');

  console.log(`Created ${outputPath}`);
  console.log(
    `Plugin: ${plugin.id} (${uniqueTargets.length} target${uniqueTargets.length === 1 ? '' : 's'}: ${uniqueTargets.join(', ')})`,
  );
  console.log('Next: edit the config and replace ./TODO with actual paths in your project.');
}
